#!/bin/bash
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias __git_ps1="git branch 2>/dev/null | grep '*' | sed 's/* \(.*\)/(\1)/'"

# 短い
alias be='bundle exec'
alias bi='bundle install'
alias c=clear
alias  ga='git add' # http://www.catonmat.net/blog/git-aliases/から
alias  gp='git push'
alias  gl='git log'
alias  gs='git status'
alias  gd='git diff'
alias gdc='git diff --cached'
alias  gm='git commit -m'
alias gma='git commit -am'
alias  gb='git branch'
alias  gc='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gpu='git pull'
alias gcl='git clone'
alias  gnc='geeknote create'
alias  gne='geeknote edit'
alias gnen='geeknote edit --note'
alias gnfs='geeknote find --search'
alias gnli='geeknote login'
alias gnnl='geeknote notebook-list'
alias  gns='geeknote show'
alias gntl='geeknote tag-list'
alias q=exit
alias r=rails
alias R='R --vanilla'
alias tmux="tmux -2"
alias yt='youtube-dl -t'
alias yt_dl_mp3='youtube-dl -t --extract-audio --audio-format mp3 --audio-quality 5'

# 普通な違いのために
alias cd-='cd - '
alias cd..='cd ..'
alias cdd='cd - '
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

