#!/bin/bash
# Add paths to PATH
export PATH=~/.bin:~/.bin/tmux-sessions:${PATH} # Add ~/.bin
export PATH=${PATH}:$HOME/.rvm/bin # Add RVM 

# For tmux
export TERM=xterm-256color

export LC_CTYPE=en_US.UTF-8

