call dein#add('benmills/vimux', {'on_ft': 'ruby'})
call dein#add('ecomba/vim-ruby-refactoring', {'on_ft': 'ruby'})
call dein#add('Keithbsmiley/rspec.vim', {'on_ft': 'ruby'})
call dein#add('jgdavey/tslime.vim', {'on_ft': 'ruby'})
call dein#add('thoughtbot/vim-rspec', {'on_ft': 'ruby'})
call dein#add('vim-ruby/vim-ruby', {'on_ft': 'ruby'})
