call dein#add('benmills/vimux')
call dein#add('ecomba/vim-ruby-refactoring')
call dein#add('Keithbsmiley/rspec.vim')
call dein#add('jgdavey/tslime.vim')
call dein#add('thoughtbot/vim-rspec')
call dein#add('tpope/vim-endwise')
call dein#add('vim-ruby/vim-ruby')
