#!/usr/bin/env ruby

class AudioSplitter
  EXECUTABLE = "avconv"

  def initialize
    print_usage_and_exit unless ARGV.count.between?(3, 5)
    parse_arguments
  end

  def run
    infile_arg = "-i #{@infile}"
    start_arg = "-ss #{@startsection}"
    duration_arg = "-t #{@duration}"
    if @volume_amplification
      vol_arg = "-vol #{volume_amplifier}"
      args = [EXECUTABLE, infile_arg, start_arg, duration_arg, vol_arg, @outfile]
    else
      codec_arg = "-acodec copy"
      args = [EXECUTABLE, infile_arg, codec_arg, start_arg, duration_arg, @outfile]
    end

    %x(#{args.join(" ")})
    exit
  end

  private

  def set_outfiles_name
    @outfile = "#{File.basename(@infile, @infile_extention)}-#{@startsection.gsub(":", "")}.#{@outfile_extention}"
  end

  def parse_arguments
    @infile = ARGV[0]
    @infile_extention = File.extname(@infile)
    @startsection = ARGV[1]
    @duration = ARGV[2]
    @outfile_extention = ARGV[4] || @infile_extention.gsub(".", "")
    @volume_amplification = ARGV[5]
    set_outfiles_name
  end

  def print_usage_and_exit
    abort(
      ["Please call #{File.basename($0)} with 3 to 5 arguments:",
       "- name                   (e.g. '01.mp4')",
       "- start time             (e.g. '105.670' or '00:01:45.670')",
       "- duration               (e.g.   '4.500' or '00:00:04.500')",
       "- output file extention  (e.g. 'mp3') *OPTIONAL*",
       "- volume amplification   (e.g. '3')    *OPTIONAL*"
    ].join("\n")
    )
  end

  def volume_amplifier
    256 * @volume_amplification
  end

end

if __FILE__ == $0
  AudioSplitter.new.run
end

