#!/usr/bin/env sh
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
NPM_CONFIG_HOME="$XDG_CONFIG_HOME/npm"
export NPM_CONFIG_USERCONFIG="$NPM_CONFIG_HOME/rc"
export NPM_CONFIG_INIT_MODULE="$NPM_CONFIG_HOME/init"
